// <auto-generated />
namespace Prog5Assessment.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CustomPrices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomPrices));
        
        string IMigrationMetadata.Id
        {
            get { return "201410192055216_CustomPrices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
